ui/src/components/GettingStarted/GettingStarted.tsx

* disable image preview on cloudera image

Turn off image preview

---

llm-service/app/routers/index/__init__.py
llm-service/app/routers/index/amp_update/__init__.py
llm-service/app/routers/index/data_source/__init__.py
llm-service/app/routers/index/models/__init__.py
llm-service/app/routers/index/sessions/__init__.py
llm-service/app/services/caii.py
ui/src/api/modelsApi.ts
ui/src/api/utils.ts
ui/src/pages/Models/EmbeddingModelTable.tsx
ui/src/pages/Models/InferenceModelTable.tsx
ui/src/pages/Models/ModelPage.tsx
ui/src/pages/RagChatTab/RagChat.tsx

* Tag python endpoints for swagger

Better model error handling

---

.github/workflows/pr_build.yml
llm-service/app/tests/routers/index/test_data_source.py
llm-service/app/tests/routers/index/test_doc_summaries.py

* Fix python tests for route changes
* Add pytest to GHA

Pytest - Fix tests and add to GHA

---

.env.example
.gitignore
.project-metadata.yaml
llm-service/app/ai/indexing/index.py
llm-service/app/ai/indexing/readers/pdf.py
llm-service/app/ai/indexing/readers/simple_file.py
llm-service/pyproject.toml
llm-service/uv.lock

Adds docling PDF parsing support when the env variable `USE_ENHANCED_PDF_PROCESSING` is provided.

Add Docling PDF Support

---

backend/src/main/java/com/cloudera/cai/rag/external/RagBackendClient.java
backend/src/main/java/com/cloudera/cai/rag/files/RagFileSummaryReconciler.java
backend/src/test/java/com/cloudera/cai/rag/external/RagBackendClientTest.java
backend/src/test/java/com/cloudera/cai/rag/files/RagFileSummaryReconcilerTest.java
llm-service/app/ai/indexing/base.py
llm-service/app/ai/indexing/embedding_indexer.py
llm-service/app/ai/indexing/summary_indexer.py
llm-service/app/routers/index/data_source/__init__.py
llm-service/app/services/doc_summaries.py
llm-service/app/services/models.py
llm-service/app/tests/ai/indexing/test_csv.py
llm-service/app/tests/routers/index/test_data_source.py
llm-service/app/tests/routers/index/test_doc_summaries.py

Also avoid computing the embeddings for summaries since we don't currently use them. A follow-up will handle summarization of the data source itself.

Refactor summary index to isolate the logic

---

backend/src/main/java/com/cloudera/cai/rag/external/RagBackendClient.java
backend/src/test/java/com/cloudera/cai/rag/external/RagBackendClientTest.java
backend/src/test/java/com/cloudera/cai/rag/files/RagFileSummaryReconcilerTest.java
llm-service/app/routers/index/data_source/__init__.py
llm-service/app/services/utils.py
llm-service/app/tests/conftest.py
llm-service/app/tests/routers/index/test_data_source.py
llm-service/app/tests/routers/index/test_doc_summaries.py

1. Put the `doc_id` in the path for triggering index and summary computation
2. Sort the paths to be in alphabetical order

Shuffle API for data sources for easier human consumption

---

llm-service/app/rag_types.py
llm-service/app/routers/index/sessions/__init__.py
llm-service/app/services/chat.py
llm-service/app/services/llm_completion.py
llm-service/app/services/querier.py
llm-service/app/tests/services/test_chat.py
ui/src/api/chatApi.ts
ui/src/pages/RagChatTab/ChatOutput/Placeholders/SuggestedQuestionsCards.tsx
ui/src/pages/RagChatTab/FooterComponents/RagChatQueryInput.tsx

* And turn off question synthesis for the suggested questions queries

provide some configuration options for tweaking the chunk retrieval strategies

---

.project-metadata.yaml

Update project metadata to use jobs instead of sessions for amp setup.

Update project metadata 

---

llm-service/app/services/metrics.py
llm-service/app/tests/services/test_metrics.py

Do string comparisons, because MLflow casts everything to strings 🤷

Fix app metrics filtering

---

.env.example
llm-service/app/routers/index/models/__init__.py
llm-service/app/services/models.py
llm-service/pyproject.toml
llm-service/uv.lock
scripts/validator/validate_env.py
ui/src/api/modelsApi.ts

* Adds support for Azure OpenAI models
* Reworks the env variables validator

Add support for Azure

---

llm-service/app/services/models/__init__.py
llm-service/app/services/models/_azure_model_provider.py
llm-service/app/services/models/_bedrock_model_provider.py
llm-service/app/services/models/_caii_model_provider.py
llm-service/app/services/models/_model_provider.py
llm-service/app/services/query/query_configuration.py

Thanks Elijah for [the idea](https://github.com/cloudera/CML_AMP_RAG_Studio/pull/141#issuecomment-2690931209)!

Use a `ModelProvider` interface

---

llm-service/app/services/caii/caii.py
llm-service/app/services/mlflow/__init__.py
ui/src/api/chatApi.ts
ui/src/main.tsx
ui/src/pages/RagChatTab/ChatOutput/ChatMessages/ChatMessageController.tsx
ui/src/routes/__root.tsx
ui/src/routes/_layout/sessions/index.tsx
ui/src/routes/index.lazy.tsx
ui/src/routes/index.tsx
ui/tsconfig.json

And, stop using user-entered data to save mlflow experiment names.

Fix bug with initial questions not rendering properly 

---

llm-service/app/routers/index/chat/__init__.py
llm-service/app/routers/index/sessions/__init__.py
llm-service/app/services/chat.py
ui/src/api/chatApi.ts
ui/src/api/ragQueryApi.ts
ui/src/api/sessionApi.ts
ui/src/pages/RagChatTab/ChatLayout.tsx
ui/src/pages/RagChatTab/ChatOutput/ChatMessages/ChatMessageController.tsx
ui/src/pages/RagChatTab/ChatOutput/Placeholders/NoDataSourcesState.tsx
ui/src/pages/RagChatTab/ChatOutput/Placeholders/SuggestedQuestionsCards.tsx
ui/src/pages/RagChatTab/FooterComponents/RagChatQueryInput.tsx
ui/src/pages/RagChatTab/Sessions/SessionItem.tsx

* move suggested questions to a chat api endpoint
* bug fix with select knowledge base with no chat history

fix: move suggested questions to chat api, and bug fix

---

backend/src/main/java/com/cloudera/cai/rag/sessions/SessionService.java
backend/src/test/java/com/cloudera/cai/rag/TestData.java
backend/src/test/java/com/cloudera/cai/rag/sessions/SessionControllerTest.java
backend/src/test/java/com/cloudera/cai/rag/sessions/SessionRepositoryTest.java
backend/src/test/java/com/cloudera/cai/rag/sessions/SessionServiceTest.java
ui/src/pages/DataSources/DataSourcesManagement/DataSourcesForm.tsx

* validate sessions have valid data sources
* remove extras from data source creation

Pre-release polish

---

llm-service/app/ai/indexing/summary_indexer.py
llm-service/app/routers/index/sessions/__init__.py
llm-service/app/services/chat/__init__.py
llm-service/app/services/chat/chat.py
llm-service/app/services/chat/streaming_chat.py
llm-service/app/services/chat/suggested_questions.py
llm-service/app/services/chat/utils.py
llm-service/app/services/llm_completion.py
llm-service/app/services/models/llm.py
llm-service/app/services/query/querier.py
llm-service/app/services/session.py
llm-service/app/tests/services/test_chat.py
scripts/release_version.txt
ui/package.json
ui/pnpm-lock.yaml
ui/src/api/chatApi.ts
ui/src/api/modelsApi.ts
ui/src/api/utils.ts
ui/src/pages/RagChatTab/ChatLayout.tsx
ui/src/pages/RagChatTab/ChatOutput/ChatMessages/ChatMessageBody.tsx
ui/src/pages/RagChatTab/ChatOutput/ChatMessages/ChatMessageController.tsx
ui/src/pages/RagChatTab/ChatOutput/Loaders/PendingRagOutputSkeleton.tsx
ui/src/pages/RagChatTab/ChatOutput/Placeholders/SuggestedQuestionsCards.tsx
ui/src/pages/RagChatTab/ChatOutput/Sources/SourceNodes.tsx
ui/src/pages/RagChatTab/FooterComponents/RagChatQueryInput.tsx
ui/src/pages/RagChatTab/State/RagChatContext.tsx
ui/src/pages/Settings/RestartAppModal.tsx
ui/src/pages/Settings/SettingsPage.tsx

Chat is now streaming.
Fixed some logic around the progress wheel for config updates.

Release 1.18.0

---

ui/src/pages/RagChatTab/ChatOutput/ChatMessages/ChatMessageBody.tsx
ui/src/pages/RagChatTab/ChatOutput/ChatMessages/CopyButton.tsx

Add a copy button

---

llm-service/app/config.py
llm-service/app/services/amp_metadata/__init__.py
llm-service/app/services/models/embedding.py
llm-service/app/services/models/llm.py
llm-service/app/services/models/providers/openai.py
llm-service/app/services/models/reranking.py
scripts/release_version.txt
ui/src/api/ampMetadataApi.ts
ui/src/api/modelsApi.ts
ui/src/pages/Settings/AuthenticationFields.tsx
ui/src/pages/Settings/ModelProviderFields.tsx
ui/src/pages/Settings/RestartAppModal.tsx

Release 1.20.0

---

llm-service/app/services/query/agents/crewai_querier.py
llm-service/app/services/query/agents/planner_agent.py
ui/src/api/ampMetadataApi.ts
ui/src/api/chatApi.ts
ui/src/layout/Sidebar.tsx
ui/src/layout/TopNav.tsx
ui/src/pages/DataSources/DataSourcesManagement/DataSourcesForm.tsx
ui/src/pages/Models/ModelTips.tsx
ui/src/pages/RagChatTab/ChatOutput/ChatMessages/ChatMessageController.tsx
ui/src/pages/RagChatTab/ChatOutput/ChatMessages/EmptyChatState.tsx
ui/src/pages/Settings/AmpSettingsPage.tsx
ui/src/pages/Settings/RestartAppModal.tsx
ui/src/pages/Settings/SettingsNavigation.tsx

This pull request introduces multiple changes across the backend and frontend to enhance functionality, improve error handling, and update the user interface. Key updates include adjustments to execution parameters in the backend, improved error handling for API responses, and modifications to frontend components for better user experience and consistency.
- Increased `max_execution_time` from 30 to 120 seconds, `max_iter` from 5 to 15, added `max_rpm` (10), and `max_retry_limit` (5) in `assemble_crew` to allow more robust and extended processing. [[1]](diffhunk://#diff-79497db148beaeccabf43248abf45b7e3571d6208a447c3a5e22b91fee049998L154-R159) [[2]](diffhunk://#diff-79497db148beaeccabf43248abf45b7e3571d6208a447c3a5e22b91fee049998L259-R266)
- Updated `max_retries` from 3 to 5 for the …

add some simple alerts when a model does not exist

---

llm-service/app/services/query/querier.py

* fix bug with empty kb
* Update llm-service/app/services/query/querier.py
* small tweak
---------

Release 1.24.1

---

llm-service/app/services/caii/caii.py
llm-service/app/services/models/providers/caii.py
scripts/install_node.sh

* Simplify getting CAII model details for initial config query 
* Always set the nvm_dir env to be at project root

Emergency fixes
